services:
  web:
    container_name: myhousek-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # API root path - leave empty for /
      API_ROOT_PATH:
    ports:
      - "8000:8104"
    restart: always